MAT-409: Cancel donation on failed card 3DS authentication
Unless we want to make changes in matchbot as well we need to abandon
this donation and create a new one to allow the donor
to try using a different card.

Attemping to confirm a donation a second time after 3DS authentication
has been attempted leads to Stripe throwing this exception at matchbot:

  InvalidRequestException: This PaymentIntent's capture_method could not be
  updated because it has a status of requires_action. You may only update the
  capture_method of a PaymentIntent with one of the following statuses:
  requires_payment_method, requires_confirmation.