BG2-2850 – modules back to es2020 – the oldest es* option allowing dynamic imports
`error TS1323: Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'es2022', 'esnext', 'commonjs', 'amd', 'system', 'umd', 'node16', 'node18', or 'nodenext'.`