Stop many error messages showing up `npm run ci output`
Before this change we had many hundreds of lines of errors showing up,
as we ran tests, e.g.:

	ERROR: 'NG0304: 'swiper-slide' is not a known element (used in the 'HomeComponent' component template):
	1. If 'swiper-slide' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
	2. If 'swiper-slide' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.'

and
	ERROR: 'NG0303: Can't bind to 'logo' since it isn't a known property of 'biggive-hero-image' (used in the 'MetaCampaignComponent' component template).
	1. If 'biggive-hero-image' is an Angular component and it has the 'logo' input, then verify that it is a part of an @NgModule where this component is declared.
	2. If 'biggive-hero-image' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
	3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.'